
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var AdvanceDirectivesEntry = function () {
		var self = this;
		self.ProxyInvoked = '';
		self.HCPCompetency = '';
		self.Resuscitation = '';
		self.MedicationOnlyNoCPR = '';
		self.VentilationRespiratoryDistress = '';
		self.MayUseIntubation = '';
		self.NonInvasiveVentilation = '';
		self.NonInvasiveVentilationLimitedTrial = '';
		self.UseOralIMorIVAntibiotics = '';
		self.UseOralAntibioticsOnly = '';
		self.UseOralAntibioticsOnlySymptomRelief = '';
		self.MedicationAny = '';
		self.MedicationAnyForSymptomRelief = '';
		self.MedicationPainReliefOnly = '';
		self.TransfusionsAnyBloodProduct = '';
		self.AllowHospitalTransferAny = '';
		self.AllowHospitalTransferSevere = '';
		self.AllowHospitalTransferNone = '';
		self.MedicalTestsAny = '';
		self.MedicalTestsLimited = '';
		self.GiveChronicDialysis = '';
		self.ArtificiallyAdministerFluids = '';
		self.Other = '';

	};

	return new AdvanceDirectivesEntry();
};