
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var AllergySection = function () {
		var self = this;
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';
		self.Allergies = [];
		self.KnownAdverseEvents = '';
		self.PotentialAdverseEvents = '';

	};

	return new AllergySection();
};