
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var AssigningAuthorityListEntry = function () {
		var self = this;
		self.GroupIdentifier = '';
		self.Name = '';
		self.Root = '';

	};

	return new AssigningAuthorityListEntry();
};