
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var Author = function () {
		var self = this;
		self.FirstName = '';
		self.LastName = '';
		self.UserName = '';

	};

	return new Author();
};