
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var CdaXmlDocument = function () {
		var self = this;
		self.Xml = '';

	};

	return new CdaXmlDocument();
};