
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var DocumentStatusCode = require("../Model/Enum/enum.js").DocumentStatusCode;
var documentInfo = require("./DocumentInfo.js").create();
var cdaXmlDocument = require("./CdaXmlDocument.js").create();
var problemSection = require("./ProblemSection.js").create();
var vitalsSection = require("./VitalsSection.js").create();
var medicationSection = require("./MedicationSection.js").create();
var advanceDirectivesSection = require("./AdvanceDirectivesSection.js").create();
var allergiesSection = require("./AllergySection.js").create();
var assessmentSection = require("./GenericSection.js").create();
var chiefComplaintSection = require("./GenericSection.js").create();
var physicalExamSection = require("./GenericSection.js").create();
var familyHistorySection = require("./GenericSection.js").create();
var historyOfPresentIllnessSection = require("./GenericSection.js").create();
var historyOfPastIllnessSection = require("./PastIllnessSection.js").create();
var hospitalDischargeDiagnosisSection = require("./GenericSection.js").create();
var immunizationSection = require("./GenericSection.js").create();
var medicalEquipmentSection = require("./MedicalEquipmentSection.js").create();
var payerSection = require("./PayerSection.js").create();
var encounterSection = require("./EncountersSection.js").create();
var planOfCareSection = require("./PlanOfCareSection.js").create();
var proceduresSection = require("./GenericSection.js").create();
var resultsSection = require("./ResultsSection.js").create();
var socialHistorySection = require("./SocialHistorySection.js").create();
var functionalStatusSection = require("./FunctionalStatusSection.js").create();

exports.create = function () {
	var Document = function () {
		var self = this;
		self.CdaXmlDocument = cdaXmlDocument;
		self.DocumentInfo = documentInfo;
		self.ProblemSection = problemSection;
		self.VitalsSection = vitalsSection;
		self.MedicationSection = medicationSection;
		self.AdvanceDirectivesSection = advanceDirectivesSection;
		self.AllergiesSection = allergiesSection;
		self.AssessmentSection = assessmentSection;
		self.PhysicalExamSection = physicalExamSection;
		self.ChiefComplaintSection = chiefComplaintSection;
		self.EncounterSection = encounterSection;
		self.FamilyHistorySection = familyHistorySection;
		self.FunctionalStatusSection = functionalStatusSection;
		self.HistoryOfPresentIllnessSection = historyOfPresentIllnessSection;
		self.HistoryOfPastIllnessSection = historyOfPastIllnessSection;
		self.HospitalDischargeDiagnosisSection = hospitalDischargeDiagnosisSection;
		self.ImmunizationSection = immunizationSection;
		self.MedicalEquipmentSection = medicalEquipmentSection;
		self.PayerSection = payerSection;
		self.PlanOfCareSection = planOfCareSection;
		self.ProceduresSection = proceduresSection;
		self.ResultsSection = resultsSection;
		self.SocialHistorySection = socialHistorySection;
		self.OtherSections = [];

	};

	return new Document();
};