
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var DocumentHistory = function () {
		var self = this;
		self.HistoricalEvents = [];
		self.NewEvents = [];

	};

	return new DocumentHistory();
};