
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var DocumentSkeleton = function () {
		var self = this;
		self.Xml = '';
		self.Name = '';

	};

	return new DocumentSkeleton();
};