
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var author = require("./Author.js").create();

exports.create = function () {
	var EncountersSection = function () {
		var self = this;
		self.NumberofEDVisits = '';
		self.LastEDVisit = '';
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';
		self.Author = author;

	};

	return new EncountersSection();
};