
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var FunctionalStatusSection = function () {
		var self = this;
		self.Capabilities = [];
		self.PainScales = [];
		self.Cognitions = [];
		self.DailyLivings = [];
		self.SpecialAlerts = [];
		self.GAFScore = 0;
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';

	};

	return new FunctionalStatusSection();
};