
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var FunctionalStatusPainScaleEntry = function () {
		var self = this;
		self.id = '';
		self.PainScore = 0;
		self.PainScoreEffectiveTime = new Date();

	};

	return new FunctionalStatusPainScaleEntry();
};