
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var FunctionalStatusEntry = function () {
		var self = this;
		self.id = '';
		self.Author = {};
		self.Name = '';
		self.Value = '';
		self.EffectiveTime = new Date();

	};

	return new FunctionalStatusEntry();
};