
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var GenericSection = function () {
		var self = this;
		self.Title = '';
		self.ParentPropertyName = '';
		self.FreeNarrative = '';
		self.TransformedNarrative = '';

	};

	return new GenericSection();
};