
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var Goal = function () {
		var self = this;
		self.DesiredOutcome = '';
		self.Priority = '';
		self.Details = '';
		self.GoalDate = new Date();

	};

	return new Goal();
};