
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var patient = require("./Patient.js").create();
var author = require("./PersonInfo.js").create();
var questionContact = require("./PersonInfo.js").create();
var nextOfKin = require("./PersonInfo.js").create();
var primaryCareGiverAtHome = require("./PersonInfo.js").create();
var guardian = require("./PersonInfo.js").create();
var principleCarePhysician = require("./PersonInfo.js").create();
var carePlanManager = require("./PersonInfo.js").create();
var principleHealthCareProvider = require("./PersonInfo.js").create();
var principleCareGiver = require("./PersonInfo.js").create();
var custodian = require("./OrganizationInfo.js").create();
var sendingSite = require("./OrganizationInfo.js").create();
var sendingSite = require("./OrganizationInfo.js").create();

exports.create = function () {
	var HeaderSection = function () {
		var self = this;
		self.DocumentID = '';
		self.EncounterTime = new Date();
		self.DatePatientArrivedAtSendingSite = new Date();
		self.SendingSite = sendingSite;
		self.ClinicianToContactWithQuestions = questionContact;
		self.ReceivingSiteSentTo = '';
		self.ConfidentialityCode = 'N';
		self.Patient = patient;
		self.Authors = [author];
		self.NextOfKin = nextOfKin;
		self.PrimaryCareGiverAtHome = primaryCareGiverAtHome;
		self.Guardian = guardian;
		self.PrincipleCarePhysician = principleCarePhysician;
		self.CarePlanManager = carePlanManager;
		self.PrincipleHealthCareProvider = principleHealthCareProvider;
		self.PrincipleCareGiver = principleCareGiver;
		self.OtherMembersOfCareTeam = [];
		self.Custodian = custodian;

	};

	return new HeaderSection();
};