
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var HealthCareAgent = function () {
		var self = this;
		self.PersonInfo = '';
		self.RelationshipToPatient = '';

	};

	return new HealthCareAgent();
};