
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var user = require("./User.js").create();
var EventDirectionCode = require("../Model/Enum/enum.js").EventDirectionCode;

exports.create = function () {
	var HistoryEvent = function () {
		var self = this;
		self.Author = user;
		self.Event = '';
		self.SectionName = '';
		self.SourceDocumentId = '';
		self.SourceDocumentTitle = '';
		self.TargetDocumentTitle = '';
		self.TargetDocumentId = '';
		self.EventTime = new Date();
		self.EventDirection = EventDirectionCode.IN;

	};

	return new HistoryEvent();
};