
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var HomecareSpecificIssues = function () {
		var self = this;
		self.Address = '';
		self.Homebound = false;
		self.F2F = false;
		self.SpecificConditionsRequiringIntervention = '';
		self.StartOfCare = new Date();
		self.VerbalOrdersIssued = new Date();

	};

	return new HomecareSpecificIssues();
};