
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var author = require("./Author.js").create();

exports.create = function () {
	var ImmunizationEntry = function () {
		var self = this;
		self.id = '';
		self.Author = author;
		self.Name = '';
		self.Route = '';
		self.Dose = '';
		self.Details = '';
		self.EffectiveTime = new Date();

	};

	return new ImmunizationEntry();
};