
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var InstanceIdentifier = function () {
		var self = this;
		self.Root = '';
		self.Extension = '';

	};

	return new InstanceIdentifier();
};