
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var InstructionsAndFollowupPlans = function () {
		var self = this;
		self.ProposedInterventions = '';
		self.DegreeOfAcceptance = '';
		self.DegreeOfDiagnosticUncertainty = '';
		self.Perception = '';
		self.ScheduledAppointments = '';
		self.DischargeMedicationList = '';
		self.RedFlags = '';
		self.IdentifiedLearner = '';
		self.SpecialDiet = '';
		self.TestResultsPendingAtDischarge = '';
		self.WhoFollowsUp = '';
		self.ResultNumbers = '';
		self.ExpectedOutcomes = '';
		self.WoundCareSheetAttached = false;
		self.WoundVACDressing = '';
		self.WoundVACDressingSetting = '';
		self.WoundVACDressingChanger = '';
		self.WoundVACDressingFrequency = '';
		self.WoundVACDressingTeachingMaterials = '';

	};

	return new InstructionsAndFollowupPlans();
};