
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var author = require("./Author.js").create();

exports.create = function () {
	var LabResult = function () {
		var self = this;
		self.id = '';
		self.Name = '';
		self.Value = '';
		self.Unit = '';
		self.DateObserved = '';
		self.Author = author;

	};

	return new LabResult();
};