
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var MedicalEquipmentEntry = function () {
		var self = this;
		self.Name = '';
		self.Details = '';
		self.EffectiveTime = new Date();

	};

	return new MedicalEquipmentEntry();
};