
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var MedicationEntry = function () {
		var self = this;
		self.id = '';
		self.Author = author;
		self.DrugCode = '';
		self.DrugName = '';
		self.IndicationCode = '';
		self.IndicationName = '';
		self.Prescriber = {};
		self.StartDate = new Date();
		self.EndDate = new Date();
		self.RouteCode = '';
		self.RouteName = '';
		self.Dose = 0;
		self.Frequency = 0;
		self.CurrentActive = false;
		self.Preadmission = false;
		self.Admission = false;
		self.Discharge = false;
		self.WarfarinTargetINR = 0;
		self.WarfarinPrescriberForDoseChanges = {};
		self.WarfarinHasClinicianAgreedToManage = false;
		self.WarfarinLast3Doses = 0;
		self.WarfarinRecommendedNextDose = 0;
		self.WarfarinTimingNextDose = 0;

	};

	return new MedicationEntry();
};