
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var MedicationExclusionEntry = function () {
		var self = this;
		self.id = '';
		self.Author = author;
		self.DrugCode = '';
		self.DrugName = '';
		self.IndicationCode = '';
		self.IndicationName = '';
		self.Prescriber = '';

	};

	return new MedicationExclusionEntry();
};