
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var author = require("./Author.js").create();

exports.create = function () {
	var MedicalEquipmentSection = function () {
		var self = this;
		self.MedicalEquipment = [];
		self.Supplies = [];
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';
		self.Author = author;

	};

	return new MedicalEquipmentSection();
};