
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var MedicationSection = function () {
		var self = this;
		self.Medications = [];
		self.MedicationExclusions = [];
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';

	};

	return new MedicationSection();
};