
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var MedicalSupplyEntry = function () {
		var self = this;
		self.What = '';
		self.Where = '';
		self.When = '';
		self.SuppliesOrdered = false;
		self.SuppliesSent = false;
		self.EffectiveTime = new Date();

	};

	return new MedicalSupplyEntry();
};