
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var instanceIdentifier = require("./InstanceIdentifier.js").create();

exports.create = function () {
	var OrganizationInfo = function () {
		var self = this;
		self.Id = '';
        self.GroupIdentifier = '';
		self.StreetAddress = '';
		self.City = '';
		self.State = '';
		self.ZipCode = '';
		self.Phone = '';
		self.AltPhone = '';
		self.Email = '';
		self.Name = '';
		self.Identifiers = [instanceIdentifier];

	};

	return new OrganizationInfo();
};