
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var PastIllnessSection = function () {
		var self = this;
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';
		self.PastIllnesses = [];

	};

	return new PastIllnessSection();
};