
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var diagnoser = require("./PersonInfo.js").create();

exports.create = function () {
	var PastIllnessEntry = function () {
		var self = this;
		self.id = '';
		self.Author = author;
		self.Name = '';
		self.ResolutionDate = new Date();
		self.DateOfOnset = new Date();
		self.CurrentSeverity = '';
		self.WorstSeverity = '';
		self.Diagnoser = diagnoser;

	};

	return new PastIllnessEntry();
};