
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++


exports.create = function () {
	var Patient = function () {
        var personInfo1 = require("./PersonInfo.js").create();
		var self = this;
		self.PersonInfo = personInfo1;
		self.BirthTime = null;
		self.GenderCode = '';
		self.RaceCode = '';
		self.EthnicityCode = '';
		self.PrimaryLanguageCode = '';
		self.OtherLanguageCode = '';
		self.MaritalStatusCode = '';
		self.ReligionCode = '';

	};

	return new Patient();
};