
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var PayerPolicy = function () {
		var self = this;
		self.id = '';
		self.InsurerName = [];
		self.InsurerPhone = '';
		self.PolicyNumber = '';
		self.InsuranceType = '';
		self.MemberNumber = '';
		self.PolicyDetails = '';
		self.Guarantor = '';
		self.Author = '';

	};

	return new PayerPolicy();
};