
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var instanceIdentifier = require("./InstanceIdentifier.js").create();

exports.create = function () {
	var PersonInfo = function () {
		var self = this;
		self.StreetAddress = '';
		self.City = '';
		self.State = '';
		self.ZipCode = '';
		self.Country = 'US';
		self.Phone = '';
		self.AltPhone = '';
		self.Pager = '';
		self.Email = '';
		self.NPI = '';
		self.FirstName = '';
		self.LastName = '';
        self.Suffix = '';
        self.Credentials = '';
		self.Specialty = '';
		self.RelationshipToPatient = '';
		self.Identifiers = [instanceIdentifier];

	};

	return new PersonInfo();
};