
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var author = require("./Author.js").create();
var instructionsAndFollowupPlans = require("./InstructionsAndFollowupPlans.js").create();
var homecareSpecificIssues = require("./HomecareSpecificIssues.js").create();

exports.create = function () {
	var PlanOfCareSection = function () {
		var self = this;
		self.Author = author;
		self.ClinicalAssumingResponsibility = {};
		self.ReceivedVerbalHandoff = '';
		self.ShortTermGoals = [];
		self.LongTermGoals = [];
		self.ProblemSpecificGoals = [];
		self.GoalWeight = [];
		self.DailyWeightChecks = '';
		self.Instructions = instructionsAndFollowupPlans;
		self.HomecareSpecificIssues = homecareSpecificIssues;
		self.VersionNumber = '';
		self.BasedOnVersionNumber = '';
		self.BasedOnSections = '';
		self.SignificantChanges = '';
		self.ForSpecificTeamMembers = '';
		self.ReconciledBy = {};
		self.DateReconciled = new Date();
		self.NurseReview = new Date();
		self.PhysicianReview = new Date();
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';

	};

	return new PlanOfCareSection();
};