
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var author = require("./Author.js").create();

exports.create = function () {
	var ProblemSectionProblem = function () {
		var self = this;
		self.id = '';
		self.Author = author;
		self.Name = '';
		self.Code = '';
		self.DateOfOnset = new Date();
		self.ResolutionDate = new Date();
		self.Diagnoser = '';
		self.ClinicianToCall = '';
		self.CurrentSeverity = '';
		self.CurrentSeverityName = '';
		self.WorstSeverity = '';
		self.WorstSeverityName = '';
		self.ProblemFindings = '';

	};

	return new ProblemSectionProblem();
};