
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var ProblemSection = function () {
		var self = this;
		self.LifeThreateningConditionPresent = false;
		self.DSM_AXIS_1 = '';
		self.DSM_AXIS_2 = '';
		self.DSM_AXIS_3 = '';
		self.DSM_AXIS_4 = '';
		self.Problems = [];
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';
		self.Title = 'PROBLEMS';

	};

	return new ProblemSection();
};