
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var ProblemSpecificGoal = function () {
		var self = this;
		self.DesiredOutcome = '';
		self.Milesones = '';
		self.Barriers = '';
		self.Progress = '';
		self.GoalDate = new Date();

	};

	return new ProblemSpecificGoal();
};