
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var ProblemFinding = function () {
		var self = this;
		self.Name = '';
		self.Code = '';
		self.id = '';

	};

	return new ProblemFinding();
};