
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var ProcedureSection = function () {
		var self = this;
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';
		self.ProcedureOrders = [];
		self.CommonTreatments = [];
		self.SpecializedTreatments = [];
		self.OtherTreatments = [];

	};

	return new ProcedureSection();
};