
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++

exports.create = function () {
	var SnomedProblem = function () {
		var self = this;
		self.SNOMED_CID = '';
		self.SNOMED_FSN = '';
		self.SNOMED_CONCEPT_STATUS = '';
		self.UMLS_CUI = '';
		self.OCCURRENCE = '';
		self.USAGE = '';
		self.FIRST_IN_SUBSET = '';
		self.IS_RETIRED_FROM_SUBSET = '';
		self.LAST_IN_SUBSET = '';
		self.REPLACED_BY_SNOMED_CID = '';

	};

	return new SnomedProblem();
};