
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var author = require("./Author.js").create();

exports.create = function () {
	var SocialHistorySection = function () {
		var self = this;
		self.Author = author;
		self.PatientLikesDislikes = '';
		self.PatientExpectations = '';
		self.ReligiousCulturalIssues = '';
		self.InadequateCommunitySupport = false;
		self.FamilyNotInvolvedInCare = false;
		self.Smoking = '';
		self.Alcohol = '';
		self.DrugUse = '';
		self.LifetimeRadiationExposure = '';
		self.RiskySexualBehavior = '';
		self.WorkplaceExposures = '';
		self.OtherExposures = '';
		self.HousingStatus = '';
		self.Readmission = '';
		self.Skin = '';
		self.Falls = '';
		self.MedError = '';
		self.CarePlanFailure = '';
		self.EnvironmentalFactors = '';
		self.EnvironmentalRisksDecisionModifiers = '';
		self.LastHospitalAdmission = '';
		self.HomeSupports = '';
		self.Transportation = '';
		self.LivingArrangement = '';
		self.FreeNarrative = '';
		self.GeneratedNarrative = '';
		self.TransformedNarrative = '';

	};

	return new SocialHistorySection();
};