
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var author = require("./Author.js").create();

exports.create = function () {
	var TreatmentEntry = function () {
		var self = this;
		self.id = '';
		self.Author = author;
		self.Name = '';
		self.Code = '';
		self.Value = '';
		self.EffectiveDate = new Date();

	};

	return new TreatmentEntry();
};