
//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
var personInfo = require("./PersonInfo.js").create();

exports.create = function () {
	var User = function () {
		var self = this;
		self.UserName = '';
		self.MRU = [];
		self.GroupIdentifier = '';
		self.Mailbox = '';
		self.csrfToken = '';
		self.PersonInfo = personInfo;

	};

	return new User();
};