//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++s
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
exports.DocumentStatusCode =  { };
exports.DocumentStatusCode.DRAFT = 0;
exports.DocumentStatusCode.FINAL = 1;
exports.DocumentStatusCode.SENT = 2;
exports.SectionCode =  { };
exports.SectionCode.VITAL = 0;
exports.SectionCode.PROBLEM = 1;
exports.SectionCode.ADVANCEDIRECTIVE = 2;
exports.SectionCode.ALLERGIES = 3;
exports.SectionCode.ASSESSMENT = 4;
exports.SectionCode.CHIEFCOMPLAINT = 5;
exports.SectionCode.ENCOUNTERS = 6;
exports.SectionCode.FAMILYHISTORY = 7;
exports.SectionCode.FUNCTIONALSTATUS = 8;
exports.SectionCode.HISTORYOFPRESENTILLNESS = 9;
exports.SectionCode.HISTORYOFPASTILLNESS = 10;
exports.SectionCode.HOSPITALDISCHARGEDIAGNOSIS = 11;
exports.SectionCode.IMMUNIZATION = 12;
exports.SectionCode.MEDICALEQUIPMENT = 13;
exports.SectionCode.MEDICATION = 14;
exports.SectionCode.PAYERS = 15;
exports.SectionCode.PLANOFCARE = 16;
exports.SectionCode.PROCEDURES = 17;
exports.SectionCode.RESULTS = 18;
exports.SectionCode.SOCIALHISTORY = 19;
exports.SectionCode.HEADER = 20;
exports.SectionCode.PHYSICALEXAM = 21;
exports.SectionCode.ALL = 1000;
exports.EventDirectionCode =  { };
exports.EventDirectionCode.IN = 0;
exports.EventDirectionCode.OUT = 1;
//######################################################