//+++++++++++++++++++ WARNING ++++++++++++++++++++++++++s
// This file was generated by a tool. DO NOT HAND EDIT!
//++++++++++++++++++++++++++++++++++++++++++++++++++++++
SEE.namespace("SEE.enum");
SEE.enum.DocumentStatusCode =  {
	DRAFT : 0 ,
	FINAL : 1 ,
	SENT : 2 
};
SEE.enum.DocumentStatusCode.GetValue = function (enumString) {
	var val = -1;
	switch (enumString.toLowerCase())
	{
		case 'draft':
			val = 0;
			break;
		case 'final':
			val = 1;
			break;
		case 'sent':
			val = 2;
			break;
		default:
			val = -1;
	}

	return val;
};
SEE.enum.View =  {
	DOCUMENTLIST : 0 ,
	UPLOAD : 1 ,
	DOCUMENT : 2 
};
SEE.enum.View.GetValue = function (enumString) {
	var val = -1;
	switch (enumString.toLowerCase())
	{
		case 'documentlist':
			val = 0;
			break;
		case 'upload':
			val = 1;
			break;
		case 'document':
			val = 2;
			break;
		default:
			val = -1;
	}

	return val;
};
SEE.enum.SectionCode =  {
	VITAL : 0 ,
	PROBLEM : 1 ,
	ADVANCEDIRECTIVE : 2 ,
	ALLERGIES : 3 ,
	ASSESSMENT : 4 ,
	CHIEFCOMPLAINT : 5 ,
	ENCOUNTERS : 6 ,
	FAMILYHISTORY : 7 ,
	FUNCTIONALSTATUS : 8 ,
	HISTORYOFPRESENTILLNESS : 9 ,
	HISTORYOFPASTILLNESS : 10 ,
	HOSPITALDISCHARGEDIAGNOSIS : 11 ,
	IMMUNIZATION : 12 ,
	MEDICALEQUIPMENT : 13 ,
	MEDICATION : 14 ,
	PAYERS : 15 ,
	PLANOFCARE : 16 ,
	PROCEDURES : 17 ,
	RESULTS : 18 ,
	SOCIALHISTORY : 19 ,
	HEADER : 20 ,
	PHYSICALEXAM : 21 ,
	ALL : 1000 
};
SEE.enum.SectionCode.GetValue = function (enumString) {
	var val = -1;
	switch (enumString.toLowerCase())
	{
		case 'vital':
			val = 0;
			break;
		case 'problem':
			val = 1;
			break;
		case 'advancedirective':
			val = 2;
			break;
		case 'allergies':
			val = 3;
			break;
		case 'assessment':
			val = 4;
			break;
		case 'chiefcomplaint':
			val = 5;
			break;
		case 'encounters':
			val = 6;
			break;
		case 'familyhistory':
			val = 7;
			break;
		case 'functionalstatus':
			val = 8;
			break;
		case 'historyofpresentillness':
			val = 9;
			break;
		case 'historyofpastillness':
			val = 10;
			break;
		case 'hospitaldischargediagnosis':
			val = 11;
			break;
		case 'immunization':
			val = 12;
			break;
		case 'medicalequipment':
			val = 13;
			break;
		case 'medication':
			val = 14;
			break;
		case 'payers':
			val = 15;
			break;
		case 'planofcare':
			val = 16;
			break;
		case 'procedures':
			val = 17;
			break;
		case 'results':
			val = 18;
			break;
		case 'socialhistory':
			val = 19;
			break;
		case 'header':
			val = 20;
			break;
		case 'physicalexam':
			val = 21;
			break;
		case 'all':
			val = 1000;
			break;
		default:
			val = -1;
	}

	return val;
};
SEE.enum.EventDirectionCode =  {
	IN : 0 ,
	OUT : 1 
};
SEE.enum.EventDirectionCode.GetValue = function (enumString) {
	var val = -1;
	switch (enumString.toLowerCase())
	{
		case 'in':
			val = 0;
			break;
		case 'out':
			val = 1;
			break;
		default:
			val = -1;
	}

	return val;
};
